FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

ARG REACT_APP_ADMIN_EMAIL
ARG REACT_APP_BACKEND
ARG REACT_APP_FRONTEND
ARG REACT_APP_IMGIX
ARG REACT_APP_RENTAL_IBAN
ARG REACT_APP_STRIPE_PUBLIC_KEY
ARG REACT_APP_SUPABASE_URL
ARG REACT_APP_SUPABASE_PUBLISHABLE_DEFAULT_KEY
ARG REACT_APP_SUPABASE_IMAGE

ENV REACT_APP_ADMIN_EMAIL=$REACT_APP_ADMIN_EMAIL
ENV REACT_APP_BACKEND=$REACT_APP_BACKEND
ENV REACT_APP_FRONTEND=$REACT_APP_FRONTEND
ENV REACT_APP_IMGIX=$REACT_APP_IMGIX
ENV REACT_APP_RENTAL_IBAN=$REACT_APP_RENTAL_IBAN
ENV REACT_APP_STRIPE_PUBLIC_KEY=$REACT_APP_STRIPE_PUBLIC_KEY
ENV REACT_APP_SUPABASE_URL=$REACT_APP_SUPABASE_URL
ENV REACT_APP_SUPABASE_PUBLISHABLE_DEFAULT_KEY=$REACT_APP_SUPABASE_PUBLISHABLE_DEFAULT_KEY
ENV REACT_APP_SUPABASE_IMAGE=$REACT_APP_SUPABASE_IMAGE

RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80